### ISSUE TITLE
Installer requests EAP patch 6.4.4 which does not appear to be publicly available

### ISSUE THREAD

**Issue by ediggins** [jbossdemocentral/bpms-install-demo#13]
Per the title, the 6.4.4 patch file appears to only be available via the Customer portal.

**Comment by mmeandro** [comment]
you can get it as a 90 trial version.
dont ask me how to navigate RH site to get there
but i did it ... i just have to figure it out each time... i have always had trouble with RH sign in and navigation on there web site... send me an email and try to help...mmeandro
at yahoo

**Comment by DuncanDoyle** [comment]
Sorry for the late reply on this issue, I just took over responsibility for the BxMS demo's. I'm currently chasing this problem and hopefully will be able to provided a better first experience ASAP.

**Comment by mmeandro** [comment]
ok
 

    On Wednesday, June 15, 2016 3:15 PM, DuncanDoyle <notifications@github.com> wrote:
 

 Sorry for the late reply on this issue, I just took over responsibility for the BxMS demo's. I'm currently chasing this problem and hopefully will be able to provided a better first experience ASAP.—

**Comment by alexandr-bbm** [comment]
+1

**Comment by eximius313** [comment]
@DuncanDoyle any progress on this?

**Comment by DuncanDoyle** [comment]
With the release of BPM Suite 6.4.0.GA today, which runs on EAP 7, all required downloads to run the demo should be publicly available. Links are included in the README.

Sorry this took so long, but I needed to wait for this release and its EAP 7 support to resolve this issue.

Fixed by: https://github.com/jbossdemocentral/bpms-install-demo/commit/0c95a8a82c0a5cbf86116eecd30ab5ede265b07e
